#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  selector:
    matchLabels:
      app: fastapi-server
  replicas: 1
  template:
    metadata:
      labels:
        app: fastapi-server
    spec:
      containers:
      - name: fastapi-container
        #image: gcr.io/tensorflow-serving/resnet 
        image: docker.io/yacruz/fastapiml:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: fastapi-service
  name: fastapi-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: fastapi-server
  type: LoadBalancer
